<?php

if(!defined('REAL')){exit('access denied');}

/*$CONFIG['AUTH']['LOGIN'] = 'admin';
$CONFIG['AUTH']['PASSWORD'] = 'admin';
*/
/*
$CONFIG['DB']['HOST'] = 'localhost';
$CONFIG['DB']['NAME'] = 'zerno';
$CONFIG['DB']['USER'] = 'root';
$CONFIG['DB']['PASSWORD'] = 'root';
$CONFIG['DB']['SCHEMA'] = '';
*/

$CONFIG['DB']['HOST'] = '178.150.64.249';
$CONFIG['DB']['NAME'] = 'gps_tracking';
$CONFIG['DB']['USER'] = 'db_admin';
$CONFIG['DB']['PASSWORD'] = 'go2loads';
$CONFIG['DB']['SCHEMA'] = '"tracking_data".';
