<div class="container mt-5">
    <h3 class="text-center text-warning font-weight-normal text-uppercase">Система вiдстеження кругообiгу зерна</h3>
    <div class="row justify-content-center mt-4">
        <div class="col-md-4">
            <div class="card border-white shadow-sm">
                <div class="card-body">
                    <form action="" method="post">
                        <div class="form-group">
                            <label for="login" class="text-primary font-weight-light"><i class="fa fa-user mr-2"></i>Логiн</label>
                            <input type="text" name="login" class="form-control" id="login" placeholder="admin" required>
                        </div>
                        <div class="form-group">
                            <label for="password" class="text-primary font-weight-light"><i class="fa fa-lock mr-2"></i>Пароль</label>
                            <input type="password" name="password" class="form-control" id="password" placeholder="*****" required>
                        </div>
                        <div class="form-group text-right">
                            <button type="submit" class="btn btn-primary text-uppercase font-weight-light">Авторизуватися<i class="fa fa-angle-right ml-2"></i></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>